### ISSUE TITLE
The README doesn't explain how to parallelize tests across machines

### ISSUE THREAD

**Issue by yurivict** [AdamGleave/pytest-shard#9]
It only says how to define shard numbers.

But how to tell it to submit jobs to the grid?
How to specify the submission command?

This command
> $ pytest --shard-id=I --num-shards=N

only tells pytest what shard IDs are, but not how to submit individual jobs.

**Comment by dan-blanchard** [comment]
This is just a tool that is used alongside some other process that is submitting jobs to a CI system. For example, I use this with GitHub Actions and have a matrix defined like:

```yaml
jobs:
  unit-tests:
    strategy:
      matrix:
        shard: [0, 1, 2, 3, 4, 5]
    ...
    steps:
      ...
      - name: pytest
        run: pytest --num-shards=6 --shard-id=${{ matrix.shard }}
```

Whatever system you're using for submitting the jobs will need to fill in that shard-id value per job.

**Comment by blaise-io** [comment]
In GitLab CI:

```yml
unit-tests:
  parallel: 5
  script:
    - pytest --shard-id=$((CI_NODE_INDEX-1)) --num-shards=$CI_NODE_TOTAL
```

<small>`CI_NODE_INDEX` is 1-based.</small>
